import { pgTable, serial, text, timestamp, boolean } from 'drizzle-orm/pg-core';

export const pitchApplications = pgTable('pitch_applications', {
  id: serial('id').primaryKey(),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  email: text('email').notNull(),
  linkedin: text('linkedin'),
  headquarters: text('headquarters'),
  ecosystem: text('ecosystem'),
  companyName: text('company_name').notNull(),
  companyWebsite: text('company_website'),
  roleTitle: text('role_title'),
  companyType: text('company_type'),
  healthFocus: text('health_focus'),
  workAreas: text('work_areas'),
  businessModel: text('business_model'),
  annualRevenue: text('annual_revenue'),
  pitchDeckUrl: text('pitch_deck_url'),
  marketServed: text('market_served'),
  status: text('status').default('submitted'),
  statusUpdatedAt: timestamp('status_updated_at'),
  adminNotes: text('admin_notes'),
  referenceNumber: text('reference_number'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const programmeApplications = pgTable('programme_applications', {
  id: serial('id').primaryKey(),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  email: text('email').notNull(),
  linkedin: text('linkedin'),
  headquarters: text('headquarters'),
  companyName: text('company_name').notNull(),
  companyWebsite: text('company_website'),
  roleTitle: text('role_title'),
  marketServed: text('market_served'),
  ecosystem: text('ecosystem'),
  companyType: text('company_type'),
  companyStage: text('company_stage'),
  fundingRaised: text('funding_raised'),
  companyOverviewUrl: text('company_overview_url'),
  chinaObjectives: text('china_objectives'),
  targetCustomer: text('target_customer'),
  chinaRelevance: text('china_relevance'),
  chinaEngagement: text('china_engagement'),
  chinaConcerns: text('china_concerns'),
  worthwhileOutcome: text('worthwhile_outcome'),
  consentData: boolean('consent_data').default(false),
  status: text('status').default('submitted'),
  statusUpdatedAt: timestamp('status_updated_at'),
  adminNotes: text('admin_notes'),
  referenceNumber: text('reference_number'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const speakerApplications = pgTable('speaker_applications', {
  id: serial('id').primaryKey(),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  email: text('email').notNull(),
  linkedin: text('linkedin'),
  headquarters: text('headquarters'),
  companyName: text('company_name').notNull(),
  roleTitle: text('role_title').notNull(),
  headshotUrl: text('headshot_url'),
  bio: text('bio'),
  speakingTopics: text('speaking_topics'),
  sessionFormat: text('session_format'),
  interestedEvents: text('interested_events'),
  previousExperience: text('previous_experience'),
  message: text('message'),
  consentData: boolean('consent_data').default(false),
  status: text('status').default('submitted'),
  statusUpdatedAt: timestamp('status_updated_at'),
  adminNotes: text('admin_notes'),
  referenceNumber: text('reference_number'),
  createdAt: timestamp('created_at').defaultNow(),
});
